AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless app to convert text to speech.

  '
Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME:
          Fn::Sub: ${StageName}-${BucketName}
        TABLE_NAME:
          Fn::Sub: ${StageName}-${TableName}
    MemorySize: 128
    Timeout: 3
Outputs:
  NewPostApi:
    Description: New Post API
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/new_message/
Parameters:
  BucketName:
    Type: String
  DaysToExpire:
    Default: 1
    Type: Number
  SnsTopicName:
    Type: String
  StageName:
    AllowedValues:
    - dev
    - int
    - prod
    Default: dev
    Type: String
  TableName:
    Type: String
Resources:
  ConvertFunctionExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Action:
            - dynamodb:PutItem
            - dynamodb:Query
            Effect: Allow
            Resource:
            - Fn::GetAtt:
              - MessagesTable
              - Arn
          - Action:
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
            Effect: Allow
            Resource:
            - Fn::GetAtt:
              - MessagesTable
              - StreamArn
          - Action:
            - polly:StartSpeechSynthesisTask
            Effect: Allow
            Resource:
            - '*'
          - Action:
            - s3:PutObject
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:s3:::${StageName}-${BucketName}/*
          - Action:
            - sns:Publish
            Effect: Allow
            Resource:
            - Ref: MessagesTopic
          Version: '2012-10-17'
        PolicyName: ConvertLambdaPolicy
      RoleName:
        Fn::Sub: ${StageName}-convert-lambda-execution
    Type: AWS::IAM::Role
  ConvertToAudioFunction:
    Properties:
      CodeUri: s3://say-it-build/d2a44cc2dcc91a2adbe0d07d75294c52
      Environment:
        Variables:
          SNS_TOPIC_ARN:
            Ref: MessagesTopic
      Events:
        DDBStream:
          Properties:
            BatchSize: 100
            StartingPosition: LATEST
            Stream:
              Fn::GetAtt:
              - MessagesTable
              - StreamArn
          Type: DynamoDB
      FunctionName:
        Fn::Sub: ${StageName}-convert-to-audio
      Handler: convert_to_audio.handler
      Role:
        Fn::GetAtt:
        - ConvertFunctionExecutionRole
        - Arn
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MessagesBucket:
    Properties:
      BucketName:
        Fn::Sub: ${StageName}-${BucketName}
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays:
            Ref: DaysToExpire
          Status: Enabled
    Type: AWS::S3::Bucket
  MessagesTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName:
        Fn::Sub: ${StageName}-${TableName}
      TimeToLiveSpecification:
        AttributeName: Expiration
        Enabled: true
    Type: AWS::DynamoDB::Table
  MessagesTopic:
    Properties:
      Subscription:
      - Endpoint:
          Fn::GetAtt:
          - UpdateOutputFunction
          - Arn
        Protocol: lambda
      TopicName:
        Ref: SnsTopicName
    Type: AWS::SNS::Topic
  NewMessageExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Action:
            - dynamodb:PutItem
            Effect: Allow
            Resource:
            - Fn::GetAtt:
              - MessagesTable
              - Arn
          - Action:
            - polly:DescribeVoices
            Effect: Allow
            Resource:
            - '*'
          Version: '2012-10-17'
        PolicyName: NewPostLambdaPolicy
      RoleName:
        Fn::Sub: ${StageName}-new-message-lambda-execution
    Type: AWS::IAM::Role
  NewMessageFunction:
    Properties:
      CodeUri: s3://say-it-build/d2a44cc2dcc91a2adbe0d07d75294c52
      Environment:
        Variables:
          DAYS_TO_EXPIRE:
            Ref: DaysToExpire
      Events:
        NewMessage:
          Properties:
            Method: post
            Path: /new_message
          Type: Api
      FunctionName:
        Fn::Sub: ${StageName}-new-message
      Handler: new_message.handler
      Role:
        Fn::GetAtt:
        - NewMessageExecutionRole
        - Arn
      Runtime: python3.6
    Type: AWS::Serverless::Function
  UpdateOutputFunction:
    Properties:
      CodeUri: s3://say-it-build/d2a44cc2dcc91a2adbe0d07d75294c52
      Events:
        SnsSubscription:
          Properties:
            Topic:
              Ref: MessagesTopic
          Type: SNS
      FunctionName:
        Fn::Sub: ${StageName}-update-output
      Handler: update_output.handler
      Role:
        Fn::GetAtt:
        - UpdateOutputFunctionExecutionRole
        - Arn
      Runtime: python3.6
    Type: AWS::Serverless::Function
  UpdateOutputFunctionExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            Effect: Allow
            Resource:
            - Fn::GetAtt:
              - MessagesTable
              - Arn
          - Action:
            - s3:PutObject
            - s3:GetObject
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:s3:::${StageName}-${BucketName}/*
          Version: '2012-10-17'
        PolicyName: UpdateOutputLambdaPolicy
      RoleName:
        Fn::Sub: ${StageName}-update-output-lambda-execution
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
