AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless app to convert text to speech.
Parameters:
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - int
      - prod
  TableName:
    Type: String
  BucketName:
    Type: String
  SnsTopicName:
    Type: String
  DaysToExpire:
    Type: Number
    Default: 1

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: !Sub ${StageName}-${TableName}
        BUCKET_NAME: !Sub ${StageName}-${BucketName}

Resources:
  NewMessageExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${StageName}-new-message-lambda-execution
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
      - PolicyName: NewPostLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt MessagesTable.Arn
            - Effect: Allow
              Action:
                - polly:DescribeVoices
              Resource: [ '*' ]

  ConvertFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${StageName}-convert-lambda-execution
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
      - PolicyName: ConvertLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:Query
              Resource:
                - !GetAtt MessagesTable.Arn
            - Effect: Allow
              Action:
                - dynamodb:DescribeStream
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
              Resource:
                - !GetAtt MessagesTable.StreamArn
            - Effect: Allow
              Action:
                - polly:StartSpeechSynthesisTask
              Resource: [ '*' ]
            - Effect: Allow
              Action:
                - 's3:PutObject'
              Resource:
                - !Sub 'arn:aws:s3:::${StageName}-${BucketName}/*'
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource:
                - !Ref MessagesTopic
  UpdateOutputFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${StageName}-update-output-lambda-execution
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
      - PolicyName: UpdateOutputLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource:
                - !GetAtt MessagesTable.Arn
            - Effect: Allow
              Action:
                - 's3:PutObject'
                - 's3:GetObject'
              Resource:
                - !Sub 'arn:aws:s3:::${StageName}-${BucketName}/*'

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${StageName}-${TableName}
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: Expiration

  MessagesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${StageName}-${BucketName}
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref DaysToExpire
            Status: Enabled

  MessagesTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Ref SnsTopicName
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt UpdateOutputFunction.Arn

  NewMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      FunctionName: !Sub ${StageName}-new-message
      Handler: new_message.handler
      Runtime: python3.6
      Role: !GetAtt NewMessageExecutionRole.Arn
      Events:
        NewMessage:
          Type: Api
          Properties:
              # this deploys to an Api under the stack name
              # SAM support for stages isn't that good yet
              # TODO: explicit API definition using swagger definition?
              Path: /new_message
              Method: post
      Environment:
        Variables:
          DAYS_TO_EXPIRE: !Ref DaysToExpire

  ConvertToAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      FunctionName: !Sub ${StageName}-convert-to-audio
      Handler: convert_to_audio.handler
      Runtime: python3.6
      Role: !GetAtt ConvertFunctionExecutionRole.Arn
      Events:
        DDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MessagesTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 100
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MessagesTopic

  UpdateOutputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub ${StageName}-update-output
      Handler: update_output.handler
      Runtime: python3.6
      Role: !GetAtt UpdateOutputFunctionExecutionRole.Arn
      CodeUri: app/
      Events:
        SnsSubscription:
          Type: SNS
          Properties:
            Topic:
              Ref: MessagesTopic

Outputs:
  NewPostApi:
    Description: 'New Post API'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/new_message/'
